### ISSUE TITLE
This is a front end issue

### ISSUE THREAD

**Issue by tonyplas** [Tonyplasencia/test#4]
This is a problem with the front end of our interface. People are unable to click buttons. We're using CSS, , Javascript, and HTML

How do we fix?

**Comment by Tonyplasencia** [comment]
1. First, check the coding of the buttons to make sure they are properly coded. Make sure to check the HTML, CSS, and JavaScript of the buttons to make sure they are properly coded and able to be clicked.

2. If the coding is correct, then check the browser compatibility of the buttons. Make sure the buttons are compatible with the most popular browsers and mobile devices. 

3. Make sure the buttons are accessible to all users. Use ARIA attributes to make sure the buttons are accessible to screen readers. 

4. Check the responsiveness of the buttons. Make sure the buttons are responsive on all devices and properly sized for the user's device. 

5. Test the buttons on multiple browsers and devices to make sure they are working properly and can be clicked.

**Comment by tonyplas** [comment]
Got it. I'll finish this soon.

**Comment by tonyplas** [comment]
Great! I am done with the bug! Thanks for the help @Tonyplasencia .
